calico_crds_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/operator-crds.yaml"
tigera_operator_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/tigera-operator.yaml"
calico_custom_resources_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/custom-resources.yaml"

pod_subnet: "192.168.0.0/16"